"""Subject classification: tag -> canonical subject, and keyword rules for 2026."""

SUBJECT_TAG_MAP = [
    # General Aptitude
    ("general-aptitude", "General Aptitude"),
    ("verbal-aptitude", "General Aptitude"),
    ("quantitative-aptitude", "General Aptitude"),
    ("analytical-aptitude", "General Aptitude"),
    ("spatial-aptitude", "General Aptitude"),
    ("logical-reasoning", "General Aptitude"),
    ("verbal-reasoning", "General Aptitude"),
    ("most-appropriate-word", "General Aptitude"),
    ("english-grammar", "General Aptitude"),
    ("data-interpretation", "General Aptitude"),
    ("passage-reading", "General Aptitude"),
    ("word-pairs", "General Aptitude"),
    ("word-meaning", "General Aptitude"),
    ("synonyms", "General Aptitude"),
    ("tenses", "General Aptitude"),
    ("prepositions", "General Aptitude"),
    ("fill-in-the-blanks", "General Aptitude"),
    ("sentence-ordering", "General Aptitude"),
    ("bar-graph", "General Aptitude"),
    ("pie-chart", "General Aptitude"),
    ("line-graph", "General Aptitude"),
    ("tabular-data", "General Aptitude"),
    ("scatter-plot", "General Aptitude"),
    ("radar-chart", "General Aptitude"),
    ("number-series", "General Aptitude"),
    ("coding-decoding", "General Aptitude"),
    ("direction-sense", "General Aptitude"),
    ("seating-arrangement", "General Aptitude"),
    ("family-relationship", "General Aptitude"),
    ("mirror-image", "General Aptitude"),
    ("paper-folding", "General Aptitude"),
    ("patterns-in-two-dimensions", "General Aptitude"),
    ("patterns-in-three-dimensions", "General Aptitude"),
    ("assembling-pieces", "General Aptitude"),
    ("image-rotation", "General Aptitude"),
    ("counting-figure", "General Aptitude"),
    ("narrative-sequencing", "General Aptitude"),
    ("phrase-meaning", "General Aptitude"),
    ("word-pairs", "General Aptitude"),
    ("identify-function", "General Aptitude"),
    ("grammatical-error", "General Aptitude"),
    ("odd-one", "General Aptitude"),
    ("clock-time", "General Aptitude"),
    ("calendar", "General Aptitude"),
    ("geometry", "General Aptitude"),
    ("triangles", "General Aptitude"),
    ("circles", "General Aptitude"),
    ("volume", "General Aptitude"),
    ("cube", "General Aptitude"),
    ("mensuration", "General Aptitude"),
    ("area", "General Aptitude"),
    ("speed-time-distance", "General Aptitude"),
    ("work-time", "General Aptitude"),
    ("ratio-proportion", "General Aptitude"),
    ("percentage", "General Aptitude"),
    ("profit-loss", "General Aptitude"),
    ("interest", "General Aptitude"),
    ("cost-market-price", "General Aptitude"),
    ("alligation-mixture", "General Aptitude"),
    ("venn-diagram", "General Aptitude"),
    ("statements-follow", "General Aptitude"),
    ("true-false", "General Aptitude"),
    ("match-the-following", "General Aptitude"),
    ("logical-inference", "General Aptitude"),
    ("statement-sufficiency", "General Aptitude"),
    ("binary-operation", "General Aptitude"),
    # Discrete Mathematics
    ("discrete-mathematics", "Discrete Mathematics"),
    ("set-theory&algebra", "Discrete Mathematics"),
    ("graph-theory", "Discrete Mathematics"),
    ("mathematical-logic", "Discrete Mathematics"),
    ("combinatory", "Discrete Mathematics"),
    ("first-order-logic", "Discrete Mathematics"),
    ("propositional-logic", "Discrete Mathematics"),
    ("functions", "Discrete Mathematics"),
    ("relations", "Discrete Mathematics"),
    ("group-theory", "Discrete Mathematics"),
    ("lattice", "Discrete Mathematics"),
    ("partial-order", "Discrete Mathematics"),
    ("graph-planarity", "Discrete Mathematics"),
    ("graph-isomorphism", "Discrete Mathematics"),
    ("degree-of-graph", "Discrete Mathematics"),
    ("graph-coloring", "Discrete Mathematics"),
    ("graph-connectivity", "Discrete Mathematics"),
    ("countable-uncountable-set", "Discrete Mathematics"),
    ("pigeonhole-principle", "Discrete Mathematics"),
    ("number-theory", "Discrete Mathematics"),
    ("modular-arithmetic", "Discrete Mathematics"),
    ("generating-functions", "Discrete Mathematics"),
    ("counting", "Discrete Mathematics"),
    ("catalan-number", "Discrete Mathematics"),
    ("proof", "Discrete Mathematics"),
    ("mathematical-induction", "Discrete Mathematics"),
    ("set-theory", "Discrete Mathematics"),
    ("mapping", "Discrete Mathematics"),
    ("algebra", "Discrete Mathematics"),
    # Engineering Mathematics
    ("engineering-mathematics", "Engineering Mathematics"),
    ("linear-algebra", "Engineering Mathematics"),
    ("calculus", "Engineering Mathematics"),
    ("probability", "Engineering Mathematics"),
    ("matrix", "Engineering Mathematics"),
    ("eigen-value", "Engineering Mathematics"),
    ("determinant", "Engineering Mathematics"),
    ("vector-space", "Engineering Mathematics"),
    ("system-of-equations", "Engineering Mathematics"),
    ("limits", "Engineering Mathematics"),
    ("differentiation", "Engineering Mathematics"),
    ("integration", "Engineering Mathematics"),
    ("maxima-minima", "Engineering Mathematics"),
    ("continuity", "Engineering Mathematics"),
    ("rank-of-matrix", "Engineering Mathematics"),
    ("lu-decomposition", "Engineering Mathematics"),
    ("orthonormality", "Engineering Mathematics"),
    ("singular-value-decomposition", "Engineering Mathematics"),
    ("subspace", "Engineering Mathematics"),
    ("random-variable", "Engineering Mathematics"),
    ("expectation", "Engineering Mathematics"),
    ("conditional-probability", "Engineering Mathematics"),
    ("uniform-distribution", "Engineering Mathematics"),
    ("binomial-distribution", "Engineering Mathematics"),
    ("poisson-distribution", "Engineering Mathematics"),
    ("normal-distribution", "Engineering Mathematics"),
    ("exponential-distribution", "Engineering Mathematics"),
    ("bernoulli-distribution", "Engineering Mathematics"),
    ("probability-distribution", "Engineering Mathematics"),
    ("probability-density-function", "Engineering Mathematics"),
    ("variance", "Engineering Mathematics"),
    ("bayes-theorem", "Engineering Mathematics"),
    ("independent-events", "Engineering Mathematics"),
    ("statistics", "Engineering Mathematics"),
    ("numerical-methods", "Engineering Mathematics"),
    ("numerical-computation", "Engineering Mathematics"),
    ("logarithms", "Engineering Mathematics"),
    ("summation", "Engineering Mathematics"),
    ("polynomials", "Engineering Mathematics"),
    ("quadratic-equations", "Engineering Mathematics"),
    ("inequality", "Engineering Mathematics"),
    ("absolute-value", "Engineering Mathematics"),
    # Digital Logic
    ("digital-logic", "Digital Logic"),
    ("boolean-algebra", "Digital Logic"),
    ("k-map", "Digital Logic"),
    ("number-representation", "Digital Logic"),
    ("number-system", "Digital Logic"),
    ("flip-flop", "Digital Logic"),
    ("sequential-circuit", "Digital Logic"),
    ("combinational-circuit", "Digital Logic"),
    ("digital-counter", "Digital Logic"),
    ("multiplexer", "Digital Logic"),
    ("decoder", "Digital Logic"),
    ("adder", "Digital Logic"),
    ("shift-registers", "Digital Logic"),
    ("min-no-gates", "Digital Logic"),
    ("functional-completeness", "Digital Logic"),
    ("fixed-point-representation", "Digital Logic"),
    ("floating-point-representation", "Digital Logic"),
    ("ieee-representation", "Digital Logic"),
    ("hamming-code", "Digital Logic"),
    ("binary-codes", "Digital Logic"),
    ("carry-generator", "Digital Logic"),
    ("min-sum-of-products-form", "Digital Logic"),
    ("min-products-of-sum-form", "Digital Logic"),
    ("digital-circuits", "Digital Logic"),
    ("static-hazard", "Digital Logic"),
    ("dual-function", "Digital Logic"),
    ("ripple-counter-operation", "Digital Logic"),
    ("code-words", "Digital Logic"),
    ("circuit-output", "Digital Logic"),
    ("logic-gates", "Digital Logic"),
    # Computer Organization
    ("co-and-architecture", "Computer Organization"),
    ("cache-memory", "Computer Organization"),
    ("pipelining", "Computer Organization"),
    ("machine-instruction", "Computer Organization"),
    ("addressing-modes", "Computer Organization"),
    ("interrupts", "Computer Organization"),
    ("dma", "Computer Organization"),
    ("microprogramming", "Computer Organization"),
    ("data-path", "Computer Organization"),
    ("instruction-format", "Computer Organization"),
    ("instruction-execution", "Computer Organization"),
    ("speedup", "Computer Organization"),
    ("stall", "Computer Organization"),
    ("memory-interfacing", "Computer Organization"),
    ("io-handling", "Computer Organization"),
    ("multilevel-cache", "Computer Organization"),
    ("average-memory-access-time", "Computer Organization"),
    ("translation-lookaside-buffer", "Computer Organization"),
    ("dram", "Computer Organization"),
    ("rom", "Computer Organization"),
    ("booths-algorithm", "Computer Organization"),
    ("little-endian-big-endian", "Computer Organization"),
    ("cisc-risc-architecture", "Computer Organization"),
    ("control-unit", "Computer Organization"),
    ("instruction-set-architecture", "Computer Organization"),
    ("clock-cycles", "Computer Organization"),
    ("memory-organization", "Computer Organization"),
    ("virtual-memory", "Operating Systems"),
    ("input-output", "Computer Organization"),
    ("microprocessor", "Computer Organization"),
    ("hardware", "Computer Organization"),
    # Programming in C
    ("programming-in-c", "Programming in C"),
    ("programming", "Programming in C"),
    ("parameter-passing", "Programming in C"),
    ("recursion", "Programming in C"),
    ("pointers", "Programming in C"),
    ("output", "Programming in C"),
    ("variable-scope", "Programming in C"),
    ("goto", "Programming in C"),
    ("switch-case", "Programming in C"),
    ("expression-evaluation", "Programming in C"),
    ("strings", "Programming in C"),
    ("structure", "Programming in C"),
    ("programming-constructs", "Programming in C"),
    ("aliasing", "Programming in C"),
    ("function", "Programming in C"),
    ("infix-prefix", "Programming in C"),
    ("precedence", "Programming in C"),
    # Data Structures
    ("data-structures", "Data Structures"),
    ("binary-tree", "Data Structures"),
    ("binary-search-tree", "Data Structures"),
    ("avl-tree", "Data Structures"),
    ("b-tree", "Data Structures"),
    ("binary-heap", "Data Structures"),
    ("stack", "Data Structures"),
    ("queue", "Data Structures"),
    ("linked-list", "Data Structures"),
    ("hashing", "Data Structures"),
    ("array", "Data Structures"),
    ("tree", "Data Structures"),
    ("heap", "Data Structures"),
    ("priority-queue", "Data Structures"),
    ("union", "Data Structures"),
    ("abstract-data-type", "Data Structures"),
    ("graph", "Data Structures"),
    ("b-plus-tree", "Data Structures"),
    ("n-ary-tree", "Data Structures"),
    ("linear-probing", "Data Structures"),
    ("double-hashing", "Data Structures"),
    ("uniform-hashing", "Data Structures"),
    # Algorithms
    ("algorithms", "Algorithms"),
    ("searching", "Algorithms"),
    ("sorting", "Algorithms"),
    ("quick-sort", "Algorithms"),
    ("merge-sort", "Algorithms"),
    ("heap-sort", "Algorithms"),
    ("insertion-sort", "Algorithms"),
    ("selection-sort", "Algorithms"),
    ("bubble-sort", "Algorithms"),
    ("time-complexity", "Algorithms"),
    ("asymptotic-notations", "Algorithms"),
    ("recurrence-relation", "Algorithms"),
    ("divide-and-conquer", "Algorithms"),
    ("dynamic-programming", "Algorithms"),
    ("greedy-algorithms", "Algorithms"),
    ("greedy-technique", "Algorithms"),
    ("algorithm-design", "Algorithms"),
    ("algorithm-design-techniques", "Algorithms"),
    ("minimum-spanning-tree", "Algorithms"),
    ("shortest-path", "Algorithms"),
    ("graph-algorithms", "Algorithms"),
    ("graph-search", "Algorithms"),
    ("depth-first-search", "Algorithms"),
    ("breadth-first-search", "Algorithms"),
    ("graph-matching", "Algorithms"),
    ("topological-sort", "Algorithms"),
    ("network-flow", "Algorithms"),
    ("directed-acyclic-graph", "Algorithms"),
    ("binary-search", "Algorithms"),
    ("loop-invariants", "Algorithms"),
    ("string-matching", "Algorithms"),
    ("dijkstras-algorithm", "Algorithms"),
    ("bellman-ford", "Algorithms"),
    ("prims-algorithm", "Algorithms"),
    ("huffman-code", "Algorithms"),
    ("matrix-chain-ordering", "Algorithms"),
    ("strongly-connected-components", "Algorithms"),
    ("bitonic-array", "Algorithms"),
    ("number-of-swap", "Algorithms"),
    ("space-complexity", "Algorithms"),
    ("complexity", "Algorithms"),
    # Theory of Computation
    ("theory-of-computation", "Theory of Computation"),
    ("regular-expression", "Theory of Computation"),
    ("regular-grammar", "Theory of Computation"),
    ("regular-language", "Theory of Computation"),
    ("finite-automata", "Theory of Computation"),
    ("finite-state-machines", "Theory of Computation"),
    ("context-free-grammar", "Theory of Computation"),
    ("context-free-language", "Theory of Computation"),
    ("pushdown-automata", "Theory of Computation"),
    ("recursive-and-recursively-enumerable-languages", "Theory of Computation"),
    ("turing-machine", "Theory of Computation"),
    ("decidability", "Theory of Computation"),
    ("pumping-lemma", "Theory of Computation"),
    ("closure-property", "Theory of Computation"),
    ("minimal-state-automata", "Theory of Computation"),
    ("identify-class-language", "Theory of Computation"),
    ("non-determinism", "Theory of Computation"),
    ("dpda", "Theory of Computation"),
    ("reduction", "Theory of Computation"),
    ("ambiguous", "Theory of Computation"),
    ("grammar", "Theory of Computation"),
    ("ambiguous-grammar", "Theory of Computation"),
    ("variable-binding", "Theory of Computation"),
    # Compiler Design
    ("compiler-design", "Compiler Design"),
    ("parsing", "Compiler Design"),
    ("lr-parser", "Compiler Design"),
    ("ll-parser", "Compiler Design"),
    ("syntax-directed-translation", "Compiler Design"),
    ("intermediate-code", "Compiler Design"),
    ("runtime-environment", "Compiler Design"),
    ("lexical-analysis", "Compiler Design"),
    ("first-and-follow", "Compiler Design"),
    ("code-optimization", "Compiler Design"),
    ("register-allocation", "Compiler Design"),
    ("three-address-code", "Compiler Design"),
    ("basic-blocks", "Compiler Design"),
    ("symbol-table", "Compiler Design"),
    ("assembler", "Compiler Design"),
    ("linker", "Compiler Design"),
    ("macros", "Compiler Design"),
    ("static-single-assignment", "Compiler Design"),
    ("live-variable-analysis", "Compiler Design"),
    ("viable-prefix", "Compiler Design"),
    ("backpatching", "Compiler Design"),
    ("abstract-syntax-tree", "Compiler Design"),
    ("operator-precedence", "Compiler Design"),
    ("compilation-phases", "Compiler Design"),
    ("type-checking", "Compiler Design"),
    ("intermediate-code-generation", "Compiler Design"),
    # Operating Systems
    ("operating-system", "Operating Systems"),
    ("process-synchronization", "Operating Systems"),
    ("semaphore", "Operating Systems"),
    ("process-scheduling", "Operating Systems"),
    ("cpu-scheduling", "Operating Systems"),
    ("round-robin-scheduling", "Operating Systems"),
    ("srtf", "Operating Systems"),
    ("average-turnaround-time", "Operating Systems"),
    ("virtual-memory", "Operating Systems"),
    ("page-replacement", "Operating Systems"),
    ("paging", "Operating Systems"),
    ("demand-paging", "Operating Systems"),
    ("multilevel-paging", "Operating Systems"),
    ("page-fault", "Operating Systems"),
    ("fragmentation", "Operating Systems"),
    ("internal-fragmentation", "Operating Systems"),
    ("disk", "Operating Systems"),
    ("disk-scheduling", "Operating Systems"),
    ("threads", "Operating Systems"),
    ("file-system", "Operating Systems"),
    ("system-call", "Operating Systems"),
    ("system-calls", "Operating Systems"),
    ("deadlock", "Operating Systems"),
    ("deadlock-prevention-avoidance-detection", "Operating Systems"),
    ("context-switch", "Operating Systems"),
    ("fork-system-call", "Operating Systems"),
    ("inter-process-communication", "Operating Systems"),
    ("resource-allocation", "Operating Systems"),
    ("os-protection", "Operating Systems"),
    ("process", "Operating Systems"),
    ("processes", "Operating Systems"),
    ("concurrency", "Operating Systems"),
    ("memory-management", "Operating Systems"),
    ("precedence-graph", "Operating Systems"),
    ("bankers-algorithm", "Operating Systems"),
    ("resource-allocation-graph", "Operating Systems"),
    # Databases (DBMS)
    ("databases", "Databases (DBMS)"),
    ("sql", "Databases (DBMS)"),
    ("database-normalization", "Databases (DBMS)"),
    ("relational-algebra", "Databases (DBMS)"),
    ("relational-calculus", "Databases (DBMS)"),
    ("tuple-relational-calculus", "Databases (DBMS)"),
    ("transaction-and-concurrency", "Databases (DBMS)"),
    ("er-diagram", "Databases (DBMS)"),
    ("indexing", "Databases (DBMS)"),
    ("functional-dependency", "Databases (DBMS)"),
    ("joins", "Databases (DBMS)"),
    ("natural-join", "Databases (DBMS)"),
    ("candidate-key", "Databases (DBMS)"),
    ("referential-integrity", "Databases (DBMS)"),
    ("conflict-serializable", "Databases (DBMS)"),
    ("two-phase-locking-protocol", "Databases (DBMS)"),
    ("timestamp-ordering", "Databases (DBMS)"),
    ("relational-model", "Databases (DBMS)"),
    ("safe-query", "Databases (DBMS)"),
    ("database-design", "Databases (DBMS)"),
    ("multivalued-dependency-4nf", "Databases (DBMS)"),
    ("decomposition", "Databases (DBMS)"),
    ("query", "Databases (DBMS)"),
    ("canonical-normal-form", "Databases (DBMS)"),
    ("integrity-constraints", "Databases (DBMS)"),
    # Computer Networks
    ("computer-networks", "Computer Networks"),
    ("tcp", "Computer Networks"),
    ("udp", "Computer Networks"),
    ("ip-addressing", "Computer Networks"),
    ("subnetting", "Computer Networks"),
    ("routing", "Computer Networks"),
    ("sliding-window", "Computer Networks"),
    ("ethernet", "Computer Networks"),
    ("csma-cd", "Computer Networks"),
    ("error-detection", "Computer Networks"),
    ("application-layer-protocols", "Computer Networks"),
    ("network-protocols", "Computer Networks"),
    ("ip-packet", "Computer Networks"),
    ("congestion-control", "Computer Networks"),
    ("stop-and-wait", "Computer Networks"),
    ("lan-technologies", "Computer Networks"),
    ("distance-vector-routing", "Computer Networks"),
    ("network-layering", "Computer Networks"),
    ("osi-model", "Computer Networks"),
    ("mac-protocol", "Computer Networks"),
    ("crc-polynomial", "Computer Networks"),
    ("sockets", "Computer Networks"),
    ("bridges", "Computer Networks"),
    ("icmp", "Computer Networks"),
    ("arp", "Computer Networks"),
    ("token-bucket", "Computer Networks"),
    ("pure-aloha", "Computer Networks"),
    ("network-switching", "Computer Networks"),
    ("routing-protocols", "Computer Networks"),
    ("channel-utilization", "Computer Networks"),
    ("network-security", "Computer Networks"),
    ("network-topologies", "Computer Networks"),
    ("dns", "Computer Networks"),
    ("http", "Computer Networks"),
    ("web-technology", "Computer Networks"),
]

SUBJECT_ORDER = [
    "General Aptitude",
    "Engineering Mathematics",
    "Discrete Mathematics",
    "Digital Logic",
    "Computer Organization",
    "Programming in C",
    "Data Structures",
    "Algorithms",
    "Theory of Computation",
    "Compiler Design",
    "Operating Systems",
    "Databases (DBMS)",
    "Computer Networks",
]

# Keyword rules for 2026 official papers (no tags available).
# Each rule: (subject, [list of case-insensitive keywords]). First match wins.
SUBJECT_KEYWORDS = [
    ("General Aptitude", ["antonym", "synonym", "sentence", "analogy", "analog",
     "verbal", "grammatical", "missing tile", "fold", "dice", "logical",
     "statement is", "passage", "water", "panel", "sports", "course", "student",
     "credits", "professor", "institute", "speech", "word", "peacock", "tile",
     "grid of cells", "shaded", "highway", "salesperson", "stock", "investor",
     "profit", "friend", "family", "spell", "idiom", "aptitude"]),
    ("Digital Logic", ["boolean", "flip-flop", "karnaugh", "k-map", "logic gate",
     "gate output", "counter", "circuit", "truth table", "combinational",
     "sequential circuit", "minterm", "maxterm", "state table", "next state",
     "d flip", "sequential", "multiplexer", "decoder", "saturating up/down counter"]),
    ("Computer Organization", ["cache", "pipeline", "pipelining", "addressing mode",
     "instruction set", "memory access", "tlb", "page table", "clock cycle",
     "cpu", "register", "dma", "interrupt", "byte-addressable", "word-addressable",
     "branch", "hazard", "micro", "risc", "cisc", "endian", "cache miss",
     "hit ratio", "throughput", "instruction fetch", "assembly", "x86",
     "main memory", "cache memory", "virtual address", "physical address",
     "direct mapping", "set-associative", "fully associative", "speculative"]),
    ("Operating Systems", ["semaphore", "deadlock", "mutex", "process", "thread",
     "scheduling", "page fault", "paging", "page replacement", "virtual memory",
     "disk", "file system", "system call", "fork", "synchronization",
     "monitor", "critical section", "turnaround", "waiting time", "fifo page",
     "lru", "aging", "banker", "resource", "context switch", "kernel",
     "time quantum", "preemptive", "process state", "reader", "writer",
     "producer", "consumer", "dining", "fragmentation", "thrashing", "segmentation"]),
    ("Databases (DBMS)", ["sql", "relation", "relational", "tuple", "attribute",
     "primary key", "foreign key", "candidate key", "normal form", "bcnf",
     "functional dependency", "join", "schema", "transaction", "serializable",
     "isolation", "locking", "er model", "entity", "query", "select", "database",
     "index", "view", "triggers", "sql query", "natural join", "referential",
     "decompos", "multivalued", "clause", "group by", "aggregate"]),
    ("Computer Networks", ["tcp", "udp", "ip address", "subnet", "routing",
     "ethernet", "protocol", "packet", "frame", "osi", "mac address", "switch",
     "router", "bandwidth", "latency", "collision", "window", "ack",
     "http", "dns", "tcp", "network layer", "transport layer", "link layer",
     "application layer", "ipv", "cidr", "maximum segment", "flow control",
     "congestion", "arp", "icmp", "csma", "token", "throughput network"]),
    ("Theory of Computation", ["regular language", "context-free", "context free",
     "turing", "automata", "grammar", "language l", "pumping", "decidable",
     "undecidable", "finite automata", "pushdown", "recursively enumerable",
     "regular expression", "l =", "alphabet", "string", "dfa", "nfa",
     "state machine", "formal language", "closure", "accepts the language"]),
    ("Compiler Design", ["parser", "parsing", "grammar", "lexical", "token",
     "syntax", "semantic", "intermediate code", "three-address", "symbol table",
     "compiler", "type checking", "basic block", "register allocation",
     "lr(1)", "ll(1)", "first and follow", "shift-reduce", "ambigu", "attribute"]),
    ("Algorithms", ["time complexity", "asymptotic", "big-o", "big o", "omega",
     "sorting", "sort algorithm", "merge sort", "quick sort", "heap sort",
     "binary search", "graph", "tree traversal", "dijkstra", "shortest path",
     "spanning tree", "dynamic programming", "recursion", "greedy", "divide and",
     "polynomial", "np", "algorithm", "complexity of", "runs in", "worst case",
     "best case", "average case", "recurrence", "master theorem", "o(", "θ(", "ω(",
     "comparison", "subarray", "median", "kth", "topological"]),
    ("Data Structures", ["binary search tree", "bst", "binary tree", "avl", "heap",
     "stack", "queue", "linked list", "hash", "hashing", "array", "tree with",
     "node", "leaf", "root", "parent", "depth of", "height of", "inorder",
     "preorder", "postorder", "balanced", "red-black", "splay", "priority queue",
     "min-heap", "max-heap", "deque", "circular queue", "collision"]),
    ("Programming in C", ["c program", "c code", "printf", "include <stdio", "int main",
     "pointer", "function call", "recursive function", "output of the", "program",
     "compile", "undefined behavior", "struct", "array index", "loop", "while",
     "for (", "static variable", "global variable", "stack overflow program"]),
    ("Engineering Mathematics", ["probability", "random variable", "density function",
     "matrix", "eigen", "determinant", "linear equations", "vector space",
     "gradient", "integral", "derivative", "limit", "continuous", "differential",
     "fourier", "laplace", "poisson", "normal distribution", "expectation",
     "variance", "mean", "median", "mode", "set of all", "complex number",
     "linear transformation", "rank of", "orthogonal", "null space"]),
    ("Discrete Mathematics", ["graph g", "vertices", "edges", "vertex", "edge set",
     "graph has", "bipartite", "connected graph", "planar", "euler", "hamilton",
     "permutation", "combination", "binomial", "pigeonhole", "lattice", "partial order",
     "poset", "propositional", "predicate", "boolean function f", "relation r",
     "equivalence", "partition", "function f:", "one-to-one", "onto", "set a",
     "subset", "group g", "homomorphism", "integer n", "prime", "congruence"]),
]


def subject_from_tags(tags):
    tagset = set(tags)
    for t, subj in SUBJECT_TAG_MAP:
        if t in tagset:
            return subj
    return "Unclassified"


def subject_from_keywords(text, exclude=None):
    low = " " + text.lower() + " "
    for subj, kws in SUBJECT_KEYWORDS:
        if exclude and subj in exclude:
            continue
        for kw in kws:
            if kw in low:
                return subj
    return "Unclassified"
