"""Per-subject subtopic classification.

Two sources are combined:
  * SUBTOPIC_TAG_MAP  - exact legacy GATEOverflow tag -> subtopic (used by normalize.py)
  * SUBTOPIC_KEYWORDS - case-insensitive keyword rules for the 2026 official papers
                        which carry no tags (used by merge_2026.py).

In both maps the first match wins, so list more specific entries first.
"""

SUBTOPIC_TAG_MAP = {
    "General Aptitude": [
        # Verbal Aptitude
        ("verbal-aptitude", "Verbal Aptitude"),
        ("verbal-reasoning", "Verbal Aptitude"),
        ("most-appropriate-word", "Verbal Aptitude"),
        ("english-grammar", "Verbal Aptitude"),
        ("fill-in-the-blanks", "Verbal Aptitude"),
        ("word-pairs", "Verbal Aptitude"),
        ("word-meaning", "Verbal Aptitude"),
        ("synonyms", "Verbal Aptitude"),
        ("tenses", "Verbal Aptitude"),
        ("prepositions", "Verbal Aptitude"),
        ("phrase-meaning", "Verbal Aptitude"),
        ("grammatical-error", "Verbal Aptitude"),
        ("passage-reading", "Verbal Aptitude"),
        ("sentence-ordering", "Verbal Aptitude"),
        ("narrative-sequencing", "Verbal Aptitude"),
        # Quantitative Aptitude
        ("quantitative-aptitude", "Quantitative Aptitude"),
        ("geometry", "Quantitative Aptitude"),
        ("triangles", "Quantitative Aptitude"),
        ("circles", "Quantitative Aptitude"),
        ("volume", "Quantitative Aptitude"),
        ("cube", "Quantitative Aptitude"),
        ("mensuration", "Quantitative Aptitude"),
        ("area", "Quantitative Aptitude"),
        ("speed-time-distance", "Quantitative Aptitude"),
        ("work-time", "Quantitative Aptitude"),
        ("ratio-proportion", "Quantitative Aptitude"),
        ("percentage", "Quantitative Aptitude"),
        ("profit-loss", "Quantitative Aptitude"),
        ("interest", "Quantitative Aptitude"),
        ("cost-market-price", "Quantitative Aptitude"),
        ("alligation-mixture", "Quantitative Aptitude"),
        ("number-series", "Quantitative Aptitude"),
        ("binary-operation", "Quantitative Aptitude"),
        ("calendar", "Quantitative Aptitude"),
        ("clock-time", "Quantitative Aptitude"),
        ("data-interpretation", "Quantitative Aptitude"),
        ("bar-graph", "Quantitative Aptitude"),
        ("pie-chart", "Quantitative Aptitude"),
        ("line-graph", "Quantitative Aptitude"),
        ("tabular-data", "Quantitative Aptitude"),
        ("scatter-plot", "Quantitative Aptitude"),
        ("radar-chart", "Quantitative Aptitude"),
        # Logical & Analytical Reasoning
        ("logical-reasoning", "Logical & Analytical Reasoning"),
        ("analytical-aptitude", "Logical & Analytical Reasoning"),
        ("coding-decoding", "Logical & Analytical Reasoning"),
        ("direction-sense", "Logical & Analytical Reasoning"),
        ("seating-arrangement", "Logical & Analytical Reasoning"),
        ("family-relationship", "Logical & Analytical Reasoning"),
        ("venn-diagram", "Logical & Analytical Reasoning"),
        ("statements-follow", "Logical & Analytical Reasoning"),
        ("true-false", "Logical & Analytical Reasoning"),
        ("match-the-following", "Logical & Analytical Reasoning"),
        ("logical-inference", "Logical & Analytical Reasoning"),
        ("statement-sufficiency", "Logical & Analytical Reasoning"),
        ("odd-one", "Logical & Analytical Reasoning"),
        ("identify-function", "Logical & Analytical Reasoning"),
        # Spatial Aptitude
        ("spatial-aptitude", "Spatial Aptitude"),
        ("mirror-image", "Spatial Aptitude"),
        ("paper-folding", "Spatial Aptitude"),
        ("patterns-in-two-dimensions", "Spatial Aptitude"),
        ("patterns-in-three-dimensions", "Spatial Aptitude"),
        ("assembling-pieces", "Spatial Aptitude"),
        ("image-rotation", "Spatial Aptitude"),
        ("counting-figure", "Spatial Aptitude"),
    ],
    "Engineering Mathematics": [
        # Calculus
        ("calculus", "Calculus"),
        ("limits", "Calculus"),
        ("differentiation", "Calculus"),
        ("integration", "Calculus"),
        ("maxima-minima", "Calculus"),
        ("continuity", "Calculus"),
        ("gradient", "Calculus"),
        ("fourier", "Calculus"),
        ("laplace", "Calculus"),
        ("differential-equations", "Calculus"),
        ("taylor-series", "Calculus"),
        ("maclaurin-series", "Calculus"),
        ("partial-derivatives", "Calculus"),
        ("mean-value-theorem", "Calculus"),
        # Linear Algebra
        ("linear-algebra", "Linear Algebra"),
        ("matrix", "Linear Algebra"),
        ("eigen-value", "Linear Algebra"),
        ("determinant", "Linear Algebra"),
        ("vector-space", "Linear Algebra"),
        ("system-of-equations", "Linear Algebra"),
        ("rank-of-matrix", "Linear Algebra"),
        ("lu-decomposition", "Linear Algebra"),
        ("orthonormality", "Linear Algebra"),
        ("singular-value-decomposition", "Linear Algebra"),
        ("subspace", "Linear Algebra"),
        ("linear-transformation", "Linear Algebra"),
        ("eigenvector", "Linear Algebra"),
        ("diagonalization", "Linear Algebra"),
        # Probability & Statistics
        ("probability", "Probability & Statistics"),
        ("random-variable", "Probability & Statistics"),
        ("expectation", "Probability & Statistics"),
        ("conditional-probability", "Probability & Statistics"),
        ("uniform-distribution", "Probability & Statistics"),
        ("binomial-distribution", "Probability & Statistics"),
        ("poisson-distribution", "Probability & Statistics"),
        ("normal-distribution", "Probability & Statistics"),
        ("exponential-distribution", "Probability & Statistics"),
        ("bernoulli-distribution", "Probability & Statistics"),
        ("probability-distribution", "Probability & Statistics"),
        ("probability-density-function", "Probability & Statistics"),
        ("variance", "Probability & Statistics"),
        ("bayes-theorem", "Probability & Statistics"),
        ("independent-events", "Probability & Statistics"),
        ("statistics", "Probability & Statistics"),
        ("standard-deviation", "Probability & Statistics"),
        # Numerical Methods
        ("numerical-methods", "Numerical Methods"),
        ("numerical-computation", "Numerical Methods"),
        ("newton-raphson", "Numerical Methods"),
        ("bisection", "Numerical Methods"),
        ("trapezoidal-rule", "Numerical Methods"),
        ("simpsons-rule", "Numerical Methods"),
    ],
    "Discrete Mathematics": [
        # Set Theory & Relations
        ("set-theory&algebra", "Set Theory & Relations"),
        ("set-theory", "Set Theory & Relations"),
        ("relations", "Set Theory & Relations"),
        ("functions", "Set Theory & Relations"),
        ("mapping", "Set Theory & Relations"),
        ("countable-uncountable-set", "Set Theory & Relations"),
        # Mathematical Logic
        ("mathematical-logic", "Mathematical Logic"),
        ("propositional-logic", "Mathematical Logic"),
        ("first-order-logic", "Mathematical Logic"),
        ("proof", "Mathematical Logic"),
        ("mathematical-induction", "Mathematical Logic"),
        # Combinatorics
        ("combinatory", "Combinatorics"),
        ("counting", "Combinatorics"),
        ("generating-functions", "Combinatorics"),
        ("catalan-number", "Combinatorics"),
        ("pigeonhole-principle", "Combinatorics"),
        # Graph Theory
        ("graph-theory", "Graph Theory"),
        ("graph-connectivity", "Graph Theory"),
        ("graph-planarity", "Graph Theory"),
        ("graph-coloring", "Graph Theory"),
        ("degree-of-graph", "Graph Theory"),
        ("graph-isomorphism", "Graph Theory"),
        # Group Theory & Algebra
        ("group-theory", "Group Theory & Algebra"),
        ("algebra", "Group Theory & Algebra"),
        # Number Theory
        ("number-theory", "Number Theory"),
        ("modular-arithmetic", "Number Theory"),
        # Lattice & Partial Order
        ("lattice", "Lattice & Partial Order"),
        ("partial-order", "Lattice & Partial Order"),
    ],
    "Digital Logic": [
        # Boolean Algebra
        ("boolean-algebra", "Boolean Algebra"),
        ("min-sum-of-products-form", "Boolean Algebra"),
        ("min-products-of-sum-form", "Boolean Algebra"),
        ("functional-completeness", "Boolean Algebra"),
        ("dual-function", "Boolean Algebra"),
        # K-Map & Minimization
        ("k-map", "K-Map & Minimization"),
        ("min-no-gates", "K-Map & Minimization"),
        ("static-hazard", "K-Map & Minimization"),
        # Number Systems & Representation
        ("number-representation", "Number Systems & Representation"),
        ("number-system", "Number Systems & Representation"),
        ("fixed-point-representation", "Number Systems & Representation"),
        ("floating-point-representation", "Number Systems & Representation"),
        ("ieee-representation", "Number Systems & Representation"),
        ("binary-codes", "Number Systems & Representation"),
        ("hamming-code", "Number Systems & Representation"),
        ("code-words", "Number Systems & Representation"),
        # Combinational Circuits
        ("combinational-circuit", "Combinational Circuits"),
        ("multiplexer", "Combinational Circuits"),
        ("decoder", "Combinational Circuits"),
        ("adder", "Combinational Circuits"),
        ("carry-generator", "Combinational Circuits"),
        # Sequential Circuits
        ("sequential-circuit", "Sequential Circuits"),
        ("flip-flop", "Sequential Circuits"),
        ("digital-counter", "Sequential Circuits"),
        ("shift-registers", "Sequential Circuits"),
        ("ripple-counter-operation", "Sequential Circuits"),
        # Logic Gates & Circuit Output
        ("circuit-output", "Logic Gates & Circuit Output"),
        ("logic-gates", "Logic Gates & Circuit Output"),
        ("digital-circuits", "Logic Gates & Circuit Output"),
    ],
    "Computer Organization": [
        # Memory Hierarchy & Cache
        ("cache-memory", "Memory Hierarchy & Cache"),
        ("multilevel-cache", "Memory Hierarchy & Cache"),
        ("average-memory-access-time", "Memory Hierarchy & Cache"),
        ("memory-interfacing", "Memory Hierarchy & Cache"),
        ("dram", "Memory Hierarchy & Cache"),
        ("rom", "Memory Hierarchy & Cache"),
        ("translation-lookaside-buffer", "Memory Hierarchy & Cache"),
        # Pipelining
        ("pipelining", "Pipelining"),
        ("speedup", "Pipelining"),
        ("stall", "Pipelining"),
        # Instruction Set & Addressing
        ("machine-instruction", "Instruction Set & Addressing"),
        ("addressing-modes", "Instruction Set & Addressing"),
        ("instruction-format", "Instruction Set & Addressing"),
        ("instruction-execution", "Instruction Set & Addressing"),
        ("instruction-set-architecture", "Instruction Set & Addressing"),
        # Data Path & Control Unit
        ("data-path", "Data Path & Control Unit"),
        ("control-unit", "Data Path & Control Unit"),
        ("microprogramming", "Data Path & Control Unit"),
        ("clock-cycles", "Data Path & Control Unit"),
        # I/O & Interrupts
        ("interrupts", "I/O & Interrupts"),
        ("dma", "I/O & Interrupts"),
        ("io-handling", "I/O & Interrupts"),
        ("input-output", "I/O & Interrupts"),
        # Arithmetic & Data Representation
        ("booths-algorithm", "Arithmetic & Data Representation"),
        ("little-endian-big-endian", "Arithmetic & Data Representation"),
        # Architecture
        ("cisc-risc-architecture", "Architecture"),
    ],
    "Programming in C": [
        # Functions & Recursion
        ("recursion", "Functions & Recursion"),
        ("function", "Functions & Recursion"),
        ("parameter-passing", "Functions & Recursion"),
        # Pointers & Memory
        ("pointers", "Pointers & Memory"),
        ("aliasing", "Pointers & Memory"),
        # Control Flow
        ("goto", "Control Flow"),
        ("switch-case", "Control Flow"),
        ("variable-scope", "Control Flow"),
        ("programming-constructs", "Control Flow"),
        # Expressions & Evaluation
        ("expression-evaluation", "Expressions & Evaluation"),
        ("infix-prefix", "Expressions & Evaluation"),
        # Structures
        ("structure", "Structures"),
        # Strings
        ("strings", "Strings"),
    ],
    "Data Structures": [
        # Trees
        ("binary-tree", "Trees"),
        ("binary-search-tree", "Trees"),
        ("avl-tree", "Trees"),
        ("b-tree", "Trees"),
        ("b-plus-tree", "Trees"),
        ("n-ary-tree", "Trees"),
        ("tree", "Trees"),
        # Hashing
        ("hashing", "Hashing"),
        ("linear-probing", "Hashing"),
        ("double-hashing", "Hashing"),
        ("uniform-hashing", "Hashing"),
        # Stacks & Queues
        ("stack", "Stacks & Queues"),
        ("queue", "Stacks & Queues"),
        ("priority-queue", "Stacks & Queues"),
        # Linked Lists
        ("linked-list", "Linked Lists"),
        # Heaps
        ("binary-heap", "Heaps"),
        ("heap", "Heaps"),
        # Arrays
        ("array", "Arrays"),
        # Graphs
        ("graph", "Graphs"),
        # Union-Find
        ("union", "Union-Find"),
    ],
    "Algorithms": [
        # Complexity Analysis
        ("time-complexity", "Complexity Analysis"),
        ("asymptotic-notations", "Complexity Analysis"),
        ("space-complexity", "Complexity Analysis"),
        ("loop-invariants", "Complexity Analysis"),
        # Sorting & Searching
        ("sorting", "Sorting & Searching"),
        ("quick-sort", "Sorting & Searching"),
        ("merge-sort", "Sorting & Searching"),
        ("heap-sort", "Sorting & Searching"),
        ("insertion-sort", "Sorting & Searching"),
        ("selection-sort", "Sorting & Searching"),
        ("bubble-sort", "Sorting & Searching"),
        ("searching", "Sorting & Searching"),
        ("binary-search", "Sorting & Searching"),
        ("number-of-swap", "Sorting & Searching"),
        # Recurrences & Divide & Conquer
        ("recurrence-relation", "Recurrences & Divide & Conquer"),
        # Graph Algorithms
        ("graph-algorithms", "Graph Algorithms"),
        ("minimum-spanning-tree", "Graph Algorithms"),
        ("shortest-path", "Graph Algorithms"),
        ("graph-search", "Graph Algorithms"),
        ("depth-first-search", "Graph Algorithms"),
        ("breadth-first-search", "Graph Algorithms"),
        ("dijkstras-algorithm", "Graph Algorithms"),
        ("bellman-ford", "Graph Algorithms"),
        ("prims-algorithm", "Graph Algorithms"),
        ("topological-sort", "Graph Algorithms"),
        ("strongly-connected-components", "Graph Algorithms"),
        ("directed-acyclic-graph", "Graph Algorithms"),
        ("graph-matching", "Graph Algorithms"),
        ("network-flow", "Graph Algorithms"),
        # Dynamic Programming
        ("dynamic-programming", "Dynamic Programming"),
        ("matrix-chain-ordering", "Dynamic Programming"),
        # Greedy Algorithms
        ("greedy-algorithms", "Greedy Algorithms"),
        ("huffman-code", "Greedy Algorithms"),
        # Algorithm Design
        ("algorithm-design", "Algorithm Design"),
        ("algorithm-design-techniques", "Algorithm Design"),
    ],
    "Theory of Computation": [
        # Regular Languages & Automata
        ("regular-language", "Regular Languages & Automata"),
        ("regular-expression", "Regular Languages & Automata"),
        ("regular-grammar", "Regular Languages & Automata"),
        ("finite-automata", "Regular Languages & Automata"),
        ("finite-state-machines", "Regular Languages & Automata"),
        ("minimal-state-automata", "Regular Languages & Automata"),
        ("non-determinism", "Regular Languages & Automata"),
        ("pumping-lemma", "Regular Languages & Automata"),
        ("closure-property", "Regular Languages & Automata"),
        # Context-Free Languages & PDA
        ("context-free-language", "Context-Free Languages & PDA"),
        ("context-free-grammar", "Context-Free Languages & PDA"),
        ("grammar", "Context-Free Languages & PDA"),
        ("ambiguous", "Context-Free Languages & PDA"),
        ("ambiguous-grammar", "Context-Free Languages & PDA"),
        ("pushdown-automata", "Context-Free Languages & PDA"),
        ("dpda", "Context-Free Languages & PDA"),
        ("identify-class-language", "Context-Free Languages & PDA"),
        ("variable-binding", "Context-Free Languages & PDA"),
        # Turing Machines & Recursive Languages
        ("recursive-and-recursively-enumerable-languages", "Turing Machines & Recursive Languages"),
        ("turing-machine", "Turing Machines & Recursive Languages"),
        # Decidability & Reductions
        ("decidability", "Decidability & Reductions"),
        ("reduction", "Decidability & Reductions"),
    ],
    "Compiler Design": [
        # Lexical Analysis
        ("lexical-analysis", "Lexical Analysis"),
        # Parsing
        ("parsing", "Parsing"),
        ("lr-parser", "Parsing"),
        ("ll-parser", "Parsing"),
        ("first-and-follow", "Parsing"),
        ("operator-precedence", "Parsing"),
        ("viable-prefix", "Parsing"),
        # Syntax-Directed Translation
        ("syntax-directed-translation", "Syntax-Directed Translation"),
        ("type-checking", "Syntax-Directed Translation"),
        # Intermediate Code
        ("intermediate-code", "Intermediate Code"),
        ("three-address-code", "Intermediate Code"),
        ("abstract-syntax-tree", "Intermediate Code"),
        ("backpatching", "Intermediate Code"),
        # Runtime Environments
        ("runtime-environment", "Runtime Environments"),
        # Code Optimization
        ("code-optimization", "Code Optimization"),
        ("register-allocation", "Code Optimization"),
        ("live-variable-analysis", "Code Optimization"),
        ("static-single-assignment", "Code Optimization"),
        ("basic-blocks", "Code Optimization"),
        # Assemblers, Linkers & Tools
        ("assembler", "Assemblers, Linkers & Tools"),
        ("linker", "Assemblers, Linkers & Tools"),
        ("macros", "Assemblers, Linkers & Tools"),
        ("symbol-table", "Assemblers, Linkers & Tools"),
        # Compilation Phases
        ("compilation-phases", "Compilation Phases"),
    ],
    "Operating Systems": [
        # Processes & Threads
        ("process", "Processes & Threads"),
        ("processes", "Processes & Threads"),
        ("threads", "Processes & Threads"),
        ("context-switch", "Processes & Threads"),
        ("fork-system-call", "Processes & Threads"),
        # CPU Scheduling
        ("process-scheduling", "CPU Scheduling"),
        ("cpu-scheduling", "CPU Scheduling"),
        ("round-robin-scheduling", "CPU Scheduling"),
        ("srtf", "CPU Scheduling"),
        ("average-turnaround-time", "CPU Scheduling"),
        # Synchronization & Concurrency
        ("process-synchronization", "Synchronization & Concurrency"),
        ("semaphore", "Synchronization & Concurrency"),
        ("inter-process-communication", "Synchronization & Concurrency"),
        ("concurrency", "Synchronization & Concurrency"),
        ("precedence-graph", "Synchronization & Concurrency"),
        # Deadlock
        ("deadlock-prevention-avoidance-detection", "Deadlock"),
        ("resource-allocation", "Deadlock"),
        ("resource-allocation-graph", "Deadlock"),
        # Memory Management
        ("memory-management", "Memory Management"),
        ("virtual-memory", "Memory Management"),
        ("paging", "Memory Management"),
        ("demand-paging", "Memory Management"),
        ("multilevel-paging", "Memory Management"),
        ("page-replacement", "Memory Management"),
        ("page-fault", "Memory Management"),
        ("fragmentation", "Memory Management"),
        ("internal-fragmentation", "Memory Management"),
        # File Systems & Storage
        ("file-system", "File Systems & Storage"),
        ("disk", "File Systems & Storage"),
        ("disk-scheduling", "File Systems & Storage"),
        # System Calls
        ("system-call", "System Calls"),
        ("system-calls", "System Calls"),
        # Security & Protection
        ("os-protection", "Security & Protection"),
    ],
    "Databases (DBMS)": [
        # ER & Relational Model
        ("er-diagram", "ER & Relational Model"),
        ("relational-model", "ER & Relational Model"),
        ("database-design", "ER & Relational Model"),
        # Relational Algebra & Calculus
        ("relational-algebra", "Relational Algebra & Calculus"),
        ("relational-calculus", "Relational Algebra & Calculus"),
        ("tuple-relational-calculus", "Relational Algebra & Calculus"),
        # SQL
        ("sql", "SQL"),
        ("query", "SQL"),
        ("safe-query", "SQL"),
        ("joins", "SQL"),
        ("natural-join", "SQL"),
        # Normalization
        ("database-normalization", "Normalization"),
        ("functional-dependency", "Normalization"),
        ("canonical-normal-form", "Normalization"),
        ("decomposition", "Normalization"),
        ("multivalued-dependency-4nf", "Normalization"),
        ("candidate-key", "Normalization"),
        # Integrity & Constraints
        ("integrity-constraints", "Integrity & Constraints"),
        ("referential-integrity", "Integrity & Constraints"),
        # Transactions & Concurrency
        ("transaction-and-concurrency", "Transactions & Concurrency"),
        ("conflict-serializable", "Transactions & Concurrency"),
        ("two-phase-locking-protocol", "Transactions & Concurrency"),
        ("timestamp-ordering", "Transactions & Concurrency"),
        # Indexing
        ("indexing", "Indexing"),
    ],
    "Computer Networks": [
        # Network Architecture
        ("network-layering", "Network Architecture"),
        ("osi-model", "Network Architecture"),
        # Data Link Layer
        ("ethernet", "Data Link Layer"),
        ("lan-technologies", "Data Link Layer"),
        ("mac-protocol", "Data Link Layer"),
        ("csma-cd", "Data Link Layer"),
        ("bridges", "Data Link Layer"),
        ("error-detection", "Data Link Layer"),
        ("crc-polynomial", "Data Link Layer"),
        ("network-switching", "Data Link Layer"),
        # Network Layer
        ("ip-addressing", "Network Layer"),
        ("subnetting", "Network Layer"),
        ("ip-packet", "Network Layer"),
        ("routing", "Network Layer"),
        ("routing-protocols", "Network Layer"),
        ("distance-vector-routing", "Network Layer"),
        ("arp", "Network Layer"),
        ("icmp", "Network Layer"),
        # Transport Layer
        ("tcp", "Transport Layer"),
        ("udp", "Transport Layer"),
        ("sliding-window", "Transport Layer"),
        ("congestion-control", "Transport Layer"),
        ("stop-and-wait", "Transport Layer"),
        ("token-bucket", "Transport Layer"),
        ("channel-utilization", "Transport Layer"),
        ("sockets", "Transport Layer"),
        # Application Layer
        ("application-layer-protocols", "Application Layer"),
        ("network-protocols", "Application Layer"),
        ("dns", "Application Layer"),
        ("http", "Application Layer"),
        ("web-technology", "Application Layer"),
    ],
}

# Keyword rules for the 2026 official papers (no tags). First match wins.
SUBTOPIC_KEYWORDS = {
    "General Aptitude": [
        ("Spatial Aptitude", ["fold", "dice", "mirror", "rotation", "unfold",
         "paper", "tile", "shaded", "grid of cells", "panel", "solid", "cube",
         "pattern", "unfolded", "folded", "net of"]),
        ("Quantitative Aptitude", ["percentage", "ratio", "profit", "loss",
         "interest", "distance", "speed", "work", "area of", "volume",
         "average", "fraction", "sum of", "series", "digit", "integer",
         "students", "coins", "litres", "liter", "km", "hours", "meters",
         "metres", "salary", "price", "weight", "age of", "probability of",
         "remainder", "number of", "count of", "tournament", "knock-out",
         "knock out", "matches", "credits", "enroll", "plot of", "graph below",
         "javelin", "throw", "athlete", "function of"]),
        ("Logical & Analytical Reasoning", ["statement", "logical", "reasoning",
         "code", "direction", "arrangement", "relationship", "conclusion",
         "argument", "assumption", "inference", "analogy", "definitely true",
         "cannot be", "is/are true", "highway", "express"]),
        ("Verbal Aptitude", ["word", "sentence", "synonym", "antonym",
         "grammatical", "passage", "meaning", "spell", "idiom", "preposition",
         "tense", "phrase", "vocabulary", "english", "verbal", "fill in",
         "blank", "most appropriate"]),
    ],
    "Engineering Mathematics": [
        ("Linear Algebra", ["matrix", "eigen", "determinant", "vector space",
         "linear equation", "linear system", "rank of", "lu decomposition",
         "orthonormal", "singular value", "subspace", "linear transformation",
         "trace of", "invertible", "diagonaliz", "eigenvector", "eigen value",
         "linear combination", "span of", "basis of", "inner product",
         "orthogonal projection", "least squares"]),
        ("Calculus", ["limit", "derivative", "differential", "integral",
         "integration", "continu", "maxima", "minima", "gradient", "taylor",
         "laplace", "fourier", "saddle point", "critical point", "stationary",
         "mean value theorem", "rolle", "partial derivative", "curvature",
         "converge", "sequence", "series", "increasing function", "decreasing",
         "concave", "convex", "asymptote", "domain of", "range of"]),
        ("Probability & Statistics", ["probability", "random variable", "density",
         "distribution", "expectation", "variance", "standard deviation",
         "mean", "median", "mode", "poisson", "binomial", "normal",
         "bayes", "conditional", "independent", "covariance", "correlation",
         "mutually exclusive", "sample", "regression", "permutation",
         "combination", "factorial", "randomly", "fair coin", "fair die",
         "outcome"]),
        ("Numerical Methods", ["newton-raphson", "newton raphson", "bisection",
         "numerical integration", "trapezoidal", "simpson", "false position",
         "round-off", "round off", "root of the equation", "iteration method",
         "interpolation", "newton-forward", "gauss-elimination"]),
    ],
    "Discrete Mathematics": [
        ("Mathematical Logic", ["proposition", "predicate", "quantifier",
         "tautology", "contradiction", "logically equivalent", "implies",
         "if and only if", "truth table", "first-order", "valid formula",
         "satisfiable", "negation"]),
        ("Combinatorics", ["permutation", "combination", "binomial",
         "pigeonhole", "catalan", "ways", "strings of length", "subsets",
         "arrangements", "distinct", "counting", "choose", "selections",
         "binary strings", "non-negative integer"]),
        ("Graph Theory", ["graph g", "vertices", "vertex", "edges", "edge set",
         "bipartite", "planar", "euler", "hamilton", "degree of", "subgraph",
         "connected graph", "cycle", "walk", "tree with", "spanning tree",
         "chromatic", "independent set", "cut"]),
        ("Set Theory & Relations", ["set a", "set b", "subset", "union",
         "intersection", "relation r", "equivalence relation", "reflexive",
         "symmetric", "transitive", "function f:", "one-to-one", "onto",
         "bijection", "domain", "codomain", "surjection", "injection",
         "power set"]),
        ("Group Theory & Algebra", ["group g", "subgroup", "homomorphism",
         "isomorphism", "abelian", "semigroup", "monoid", "order of",
         "coset", "group under", "binary operation"]),
        ("Number Theory", ["prime", "gcd", "modulo", "congruence", "divisible",
         "integer n", "relatively prime", "composite", "euclidean",
         "divisor"]),
        ("Lattice & Partial Order", ["lattice", "poset", "hasse", "partial order",
         "meet", "join of"]),
    ],
    "Digital Logic": [
        ("Sequential Circuits", ["flip-flop", "flip flop", "counter",
         "register", "sequential", "state diagram", "next state", "clock",
         "synchronous", "state table", "t-flip", "jk flip"]),
        ("Combinational Circuits", ["multiplexer", "mux", "decoder",
         "encoder", "adder", "combinational", "full adder", "half adder",
         "demultiplexer", "priority encoder"]),
        ("Boolean Algebra", ["boolean", "minterm", "maxterm", "sum of products",
         "product of sums", "functionally complete", "dual", "boolean function",
         "identity", "commutative law", "demorgan", "simplify the"]),
        ("K-Map & Minimization", ["k-map", "karnaugh", "essential prime",
         "implicant", "minimiz", "don't care", "don’t care", "redundant"]),
        ("Number Systems & Representation", ["binary", "hexadecimal", "octal",
         "ieee", "floating point", "floating-point", "two's complement",
         "twos complement", "signed", "bits", "mantissa", "exponent",
         "range of", "represent", "bcd", "gray code", "excess"]),
        ("Logic Gates & Circuit Output", ["logic gate", "gate", "nand",
         "nor", "xor", "x-nor", "xnor", "circuit output", "output of the",
         "logic circuit", "boolean expression for"]),
    ],
    "Computer Organization": [
        ("Pipelining", ["pipeline", "pipelining", "hazard", "stall",
         "speedup", "branch prediction", "stage", "cycle per", "cpi",
         "instruction per cycle", "forwarding"]),
        ("Memory Hierarchy & Cache", ["cache", "hit ratio", "miss rate",
         "associative", "average memory access", "tlb", "main memory",
         "block size", "cache line", "direct mapped", "set-associative",
         "am at", "memory access time", "cache size"]),
        ("Data Path & Control Unit", ["data path", "datapath", "control unit",
         "micro", "clock cycle", "alu", "register file", "instruction fetch",
         "execute", "decode", "write back", "hardwired", "control signal"]),
        ("Instruction Set & Addressing", ["addressing mode", "instruction",
         "opcode", "operand", "immediate", "instruction format", "isa",
         "assembly", "x86", "instruction set", "register addressing",
         "machine instruction"]),
        ("I/O & Interrupts", ["interrupt", "dma", "i/o", "io device",
         "polling", "interrupt handler", "input output", "input/output",
         "device controller", "handshake"]),
        ("Arithmetic & Data Representation", ["booth", "multiplication",
         "division", "endian", "unsigned number", "signed number",
         "overflow", "carry"]),
    ],
    "Programming in C": [
        ("Functions & Recursion", ["recursion", "recursive", "function call",
         "int f", "function f", "parameter", "pass by", "call by",
         "return", "void", "function returns", "recurrence in c"]),
        ("Pointers & Memory", ["pointer", "*ptr", "address of", "dereference",
         "null pointer", "malloc", "calloc", "array of pointers",
         "pointer to"]),
        ("Expressions & Evaluation", ["expression", "evaluate", "precedence",
         "associativity", "operator", "increment", "short circuit",
         "value of", "evaluates to", "side effect", "comma operator",
         "ternary", "modulo", "bitwise"]),
        ("Control Flow", ["loop", "while", "for (", "switch", "goto",
         "if condition", "break", "continue", "do while", "nested loop",
         "iterations"]),
        ("Structures", ["struct", "structure", "typedef", "union in c",
         "array of structures"]),
        ("Strings", ["string", "strcpy", "strlen", "character array",
         "char *", "strcmp", "concatenat"]),
    ],
    "Data Structures": [
        ("Trees", ["binary tree", "bst", "binary search tree", "avl",
         "b-tree", "b tree", "height of", "leaf", "inorder", "preorder",
         "postorder", "node", "root", "balanced tree", "depth of",
         "complete binary", "full binary", "internal node", "red-black",
         "splay", "ancestor", "descendant"]),
        ("Hashing", ["hash", "collision", "probe", "hash table", "load factor",
         "open addressing", "chaining", "hash function"]),
        ("Stacks & Queues", ["stack", "queue", "push", "pop", "enqueue",
         "dequeue", "lifo", "fifo", "priority queue", "deque"]),
        ("Linked Lists", ["linked list", "singly", "doubly", "circular list",
         "node next", "linked-lists"]),
        ("Heaps", ["heap", "heapify", "min-heap", "max-heap", "priority",
         "d-ary heap"]),
        ("Arrays", ["array", "subarray", "array index", "multidimensional",
         "row-major", "column-major"]),
        ("Graphs", ["adjacency", "graph traversal", "adjacency matrix",
         "adjacency list", "graph representation"]),
    ],
    "Algorithms": [
        ("Complexity Analysis", ["time complexity", "space complexity",
         "big-o", "asymptotic", "o(", "θ(", "worst case", "best case",
         "average case", "runs in", "complexity of", "upper bound",
         "lower bound", "takes"]),
        ("Recurrences & Divide & Conquer", ["recurrence", "master theorem",
         "divide and conquer", "t(n)", "t(n) =", "substitution method",
         "recurrence relation"]),
        ("Sorting & Searching", ["sort", "quick sort", "merge sort",
         "heap sort", "insertion", "selection", "bubble", "binary search",
         "searching", "comparison", "sorted array", "number of swap",
         "stable sort"]),
        ("Graph Algorithms", ["shortest path", "dijkstra", "bellman-ford",
         "spanning tree", "topological", "dfs", "bfs", "depth-first",
         "breadth-first", "network flow", "max flow", "strongly connected",
         "minimum spanning", "prim", "kruskal", "cut vertex", "biconnect",
         "articulation"]),
        ("Dynamic Programming", ["dynamic programming", "memoization",
         "subproblem", "matrix chain", "longest common", "knapsack",
         "optimal substructure", "edit distance", "lcs", "lis"]),
        ("Greedy Algorithms", ["greedy", "huffman", "fractional knapsack",
         "activity selection", "minimum coin", "optimal prefix"]),
        ("Algorithm Design", ["algorithm design", "correctness", "invariant",
         "loop invariant", "pseudo code", "pseudocode", "algorithm to"]),
    ],
    "Theory of Computation": [
        ("Regular Languages & Automata", ["regular", "dfa", "nfa",
         "finite automata", "finite state", "regular expression",
         "pumping lemma", "minimal dfa", "regular grammar", "myhill",
         "automaton"]),
        ("Context-Free Languages & PDA", ["context-free", "context free",
         "cfg", "pda", "pushdown", "ambiguous", "derivation", "parse tree",
         "grammar", "leftmost", "chomsky normal", "greibach"]),
        ("Turing Machines & Recursive Languages", ["turing", "recursively",
         "recursive language", "universal turing", "r.e.", "halting machine"]),
        ("Decidability & Reductions", ["decidable", "undecidable", "halting",
         "reduction", "rice", "post correspondence", "empty language",
         "membership problem", "complement of"]),
    ],
    "Compiler Design": [
        ("Parsing", ["parser", "parsing", "ll(1)", "lr(1)", "slr", "lalr",
         "first and follow", "first set", "follow set", "shift-reduce",
         "operator precedence", "parse table", "bottom-up", "top-down",
         "viable prefix", "handle", "stack parser", "grammar is"]),
        ("Lexical Analysis", ["lexical", "token", "lexeme", "regular expression",
         "lex", "input buffer", "tokenization"]),
        ("Syntax-Directed Translation", ["syntax-directed", "sdt",
         "attribute grammar", "synthesized", "inherited", "translation scheme",
         "semantic action", "annotated"]),
        ("Intermediate Code", ["intermediate code", "three-address",
         "quadruple", "triple", "abstract syntax", "ast", "dag",
         "backpatch", "icode", "tac"]),
        ("Runtime Environments", ["activation record", "stack frame",
         "runtime", "static scope", "dynamic scope", "environment",
         "activation tree", "display"]),
        ("Code Optimization", ["optimization", "register allocation",
         "basic block", "live variable", "ssa", "dead code", "loop",
         "graph coloring", "copy propagation", "constant folding",
         "common subexpression"]),
        ("Assemblers, Linkers & Tools", ["assembler", "linker", "loader",
         "macro", "symbol table", "relocation", "two-pass"]),
        ("Compilation Phases", ["compilation phases", "phases of", "front end",
         "back end", "lexical to", "compilation process"]),
    ],
    "Operating Systems": [
        ("Synchronization & Concurrency", ["semaphore", "mutex", "monitor",
         "critical section", "producer", "consumer", "reader", "writer",
         "dining", "synchronization", "precedence graph", "bounded buffer",
         "test-and-set", "compare-and-swap"]),
        ("Deadlock", ["deadlock", "banker", "safe state", "resource allocation",
         "wait-for", "cycle", "unsafe state", "deadlock-free"]),
        ("Memory Management", ["page table", "paging", "page replacement",
         "page fault", "virtual memory", "fifo", "lru", "thrashing",
         "segmentation", "fragmentation", "translation", "tlb",
         "demand paging", "frame", "page size", "address translation",
         "physical address", "virtual address"]),
        ("CPU Scheduling", ["scheduling", "turnaround", "waiting time",
         "round robin", "time quantum", "sjf", "response time", "throughput",
         "cpu burst", "preemptive", "srtf", "fifo scheduling",
         "schedule the"]),
        ("Processes & Threads", ["process", "thread", "fork", "context switch",
         "pid", "exec", "zombie", "process state", "process control block",
         "concurrent processes", "child process"]),
        ("File Systems & Storage", ["disk", "file system", "inode", "sector",
         "seek time", "allocation", "directory", "scsi", "raid", "c-look",
         "elevator", "cylinder"]),
        ("System Calls", ["system call", "kernel", "user mode", "privileged",
         "mode switch"]),
    ],
    "Databases (DBMS)": [
        ("Normalization", ["normal form", "bcnf", "3nf", "2nf", "1nf",
         "functional dependency", "decomposition", "lossless", "dependency preserving",
         "candidate key", "super key", "multivalued dependency", "4nf",
         "closure of", "minimal cover", "prime attribute"]),
        ("Transactions & Concurrency", ["transaction", "serializable",
         "conflict", "locking", "two-phase", "timestamp", "commit",
         "rollback", "isolation", "schedule", "deadlock", "abort",
         "recoverable", "precedence graph"]),
        ("SQL", ["sql", "select", "group by", "having", "order by",
         "aggregate", "query", "join", "natural join", "where clause",
         "nested query", "correlated", "insert", "delete", "update",
         "view", "trigger", "grant", "count(", "sum(", "avg("]),
        ("Relational Algebra & Calculus", ["relational algebra",
         "cartesian product", "division", "rename", "selection operation",
         "projection operation", "tuple relational", "domain relational",
         "natural join"]),
        ("ER & Relational Model", ["entity", "er model", "er diagram",
         "cardinality", "weak entity", "relational model", "schema",
         "attribute", "key", "strong entity", "relationship between"]),
        ("Indexing", ["index", "b+ tree", "b+ tree", "hashing index",
         "primary index", "cluster index", "dense index", "sparse index",
         "search key", "tree index", "hash index"]),
    ],
    "Computer Networks": [
        ("Network Architecture", ["osi", "tcp/ip model", "protocol stack",
         "layering", "five layers", "seven layers", "network architecture"]),
        ("Transport Layer", ["tcp", "udp", "congestion control",
         "sliding window", "ack", "segment", "handshake", "flow control",
         "window size", "ssthresh", "slow start", "rtt", "sequence number",
         "tcp header", "udp header", "pipeline"]),
        ("Network Layer", ["ip address", "subnet", "routing", "router",
         "ipv4", "ipv6", "cidr", "arp", "icmp", "packet forwarding",
         "distance vector", "link state", "routing table", "hop",
         "routing protocol", "network address", "broadcast address",
         "subnet mask"]),
        ("Data Link Layer", ["ethernet", "mac address", "frame", "csma",
         "aloha", "slotted", "collision", "error detection", "crc",
         "hamming", "data link", "bridges", "vlan", "switching", "token",
         "framing", "stop-and-wait", "go-back-n", "selective repeat",
         "bit stuffing"]),
        ("Application Layer", ["http", "dns", "ftp", "smtp",
         "application layer", "url", "web", "email", "pop3", "imap",
         "dns lookup", "server"]),
    ],
}


def subtopic_from_tags(subject, tags):
    tagset = set(tags)
    for t, sub in SUBTOPIC_TAG_MAP.get(subject, []):
        if t in tagset:
            return sub
    return None


def subtopic_from_keywords(subject, text):
    low = " " + text.lower() + " "
    for sub, kws in SUBTOPIC_KEYWORDS.get(subject, []):
        for kw in kws:
            if kw in low:
                return sub
    return None


def subtopic_for(subject, tags, text=""):
    sub = subtopic_from_tags(subject, tags)
    if sub is None:
        sub = subtopic_from_keywords(subject, text)
    return sub
